#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# attendre que postgresql soit disponible
python << END
import sys
import time

import psycopg2

while True:
    try:
        psycopg2.connect(
            dbname="${POSTGRES_DB}",
            user="${POSTGRES_USER}",
            password="${POSTGRES_PASSWORD}",
            host="${POSTGRES_HOST}",
            port="${POSTGRES_PORT}",
        )
        break
    except psycopg2.OperationalError:
        sys.stderr.write("Waiting Postgresql...\n")

    time.sleep(1)

sys.stderr.write("Postgresql is ready !\n")
END

exec "$@"